// ═══════════════════════════════════════════════════
// Task Board — Mock Data (15 realistic tasks)
// ═══════════════════════════════════════════════════

import type { EnhancedTask } from "./task-types";

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function hoursAgo(hours: number): string {
  const d = new Date();
  d.setHours(d.getHours() - hours);
  return d.toISOString();
}

export const INITIAL_TASKS: readonly EnhancedTask[] = [
  {
    id: "1",
    title: "Review Q1 Medicare claims",
    description: "Audit all Q1 Medicare claims for accuracy and compliance. Flag any discrepancies for Steward to review before submission deadline.",
    status: "in_progress",
    priority: "high",
    assigned_agent_id: "harvest",
    department_id: "accounting-finance",
    deadline: daysFromNow(2),
    created_at: daysAgo(5),
    last_viewed_by: "Lamin",
    last_viewed_at: hoursAgo(2),
    sign_off_required: true,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["medicare", "billing", "q1"],
    subtasks: [
      { id: "1-1", title: "Pull all Q1 claim records", completed: true },
      { id: "1-2", title: "Cross-reference with patient files", completed: true },
      { id: "1-3", title: "Flag discrepancies", completed: false },
      { id: "1-4", title: "Submit final report to Steward", completed: false },
    ],
    comments: [
      { id: "c1-1", author: "Harvest", text: "Found 3 discrepancies in January claims. Investigating.", created_at: hoursAgo(6) },
      { id: "c1-2", author: "Steward", text: "Priority — deadline is CMS submission window. Need this ASAP.", created_at: hoursAgo(4) },
    ],
  },
  {
    id: "2",
    title: "Complete staff satisfaction survey",
    description: "Distribute and collect responses from all active caregivers. Compile results into a summary report for Terra.",
    status: "todo",
    priority: "normal",
    assigned_agent_id: "retain",
    department_id: "caregiver-staffing",
    deadline: daysFromNow(10),
    created_at: daysAgo(3),
    last_viewed_by: "Lamin",
    last_viewed_at: daysAgo(1),
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["hr", "survey", "employee-engagement"],
    subtasks: [
      { id: "2-1", title: "Draft survey questions", completed: true },
      { id: "2-2", title: "Send to all caregivers", completed: false },
      { id: "2-3", title: "Compile results", completed: false },
    ],
    comments: [
      { id: "c2-1", author: "Terra", text: "Include questions about weekend scheduling preferences.", created_at: daysAgo(2) },
    ],
  },
  {
    id: "3",
    title: "Audit patient documentation",
    description: "Full audit of current patient charts for completeness and HIPAA compliance. Critical — state survey may occur any time.",
    status: "in_progress",
    priority: "critical",
    assigned_agent_id: "chart",
    department_id: "compliance-quality",
    deadline: daysAgo(1),
    created_at: daysAgo(7),
    last_viewed_by: "Lamin",
    last_viewed_at: hoursAgo(1),
    sign_off_required: true,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["audit", "hipaa", "compliance", "urgent"],
    subtasks: [
      { id: "3-1", title: "Review active patient charts (A-M)", completed: true },
      { id: "3-2", title: "Review active patient charts (N-Z)", completed: false },
      { id: "3-3", title: "Document findings report", completed: false },
      { id: "3-4", title: "Remediation plan", completed: false },
    ],
    comments: [
      { id: "c3-1", author: "Justice", text: "State just announced random audits in our region. This is now top priority.", created_at: daysAgo(2) },
      { id: "c3-2", author: "Chart", text: "A-M charts complete. 2 issues found and flagged.", created_at: hoursAgo(8) },
      { id: "c3-3", author: "Shield", text: "HIPAA review on flagged charts will be done by EOD.", created_at: hoursAgo(3) },
    ],
  },
  {
    id: "4",
    title: "Launch physician nurture campaign",
    description: "Execute email drip campaign targeting local physicians for referral partnerships. 6-email sequence over 30 days.",
    status: "todo",
    priority: "high",
    assigned_agent_id: "ember",
    department_id: "marketing",
    deadline: daysFromNow(5),
    created_at: daysAgo(4),
    last_viewed_by: "Camila",
    last_viewed_at: daysAgo(1),
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["email", "physician", "referral", "campaign"],
    subtasks: [
      { id: "4-1", title: "Finalize email copy (all 6)", completed: true },
      { id: "4-2", title: "Build segments in GHL", completed: true },
      { id: "4-3", title: "Set up automation triggers", completed: false },
      { id: "4-4", title: "QA test sequence", completed: false },
      { id: "4-5", title: "Launch", completed: false },
    ],
    comments: [
      { id: "c4-1", author: "Camila", text: "Copy approved. Segments look good. Proceed with automation setup.", created_at: daysAgo(1) },
    ],
  },
  {
    id: "5",
    title: "Process new referral - St. Mary Hospital",
    description: "High-priority patient referral from St. Mary Hospital. Patient is 78yo with terminal diagnosis. Family requesting immediate admission.",
    status: "in_progress",
    priority: "critical",
    assigned_agent_id: "bridge",
    department_id: "admissions-intake",
    deadline: daysFromNow(0),
    created_at: daysAgo(1),
    last_viewed_by: "River",
    last_viewed_at: hoursAgo(1),
    sign_off_required: true,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["referral", "admission", "urgent", "st-mary"],
    subtasks: [
      { id: "5-1", title: "Collect referral documentation", completed: true },
      { id: "5-2", title: "Verify insurance eligibility", completed: true },
      { id: "5-3", title: "Clinical intake assessment", completed: false },
      { id: "5-4", title: "Schedule admission visit", completed: false },
    ],
    comments: [
      { id: "c5-1", author: "Bridge", text: "Docs received from St. Mary. Insurance verified — Medicare Part A.", created_at: hoursAgo(5) },
      { id: "c5-2", author: "Verify", text: "Eligibility confirmed. Patient qualifies for full hospice benefit.", created_at: hoursAgo(3) },
      { id: "c5-3", author: "River", text: "Assign Triage for clinical intake ASAP. Family is anxious.", created_at: hoursAgo(1) },
    ],
  },
  {
    id: "6",
    title: "Update HIPAA training materials",
    description: "Refresh annual HIPAA training slide deck and quiz. Incorporate 2026 regulatory updates.",
    status: "backlog",
    priority: "normal",
    assigned_agent_id: "shield-agent",
    department_id: "compliance-quality",
    deadline: daysFromNow(30),
    created_at: daysAgo(10),
    last_viewed_by: null,
    last_viewed_at: null,
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["hipaa", "training", "compliance"],
    subtasks: [
      { id: "6-1", title: "Review 2026 regulatory changes", completed: false },
      { id: "6-2", title: "Update slide deck", completed: false },
      { id: "6-3", title: "Update quiz questions", completed: false },
    ],
    comments: [],
  },
  {
    id: "7",
    title: "Schedule caregiver coverage for weekend",
    description: "Ensure all patient visits are covered for the upcoming weekend. Two CNAs called out — need replacements.",
    status: "review",
    priority: "high",
    assigned_agent_id: "shift",
    department_id: "caregiver-staffing",
    deadline: daysFromNow(1),
    created_at: daysAgo(2),
    last_viewed_by: "Terra",
    last_viewed_at: hoursAgo(4),
    sign_off_required: true,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["scheduling", "weekend", "coverage"],
    subtasks: [
      { id: "7-1", title: "Identify open shifts", completed: true },
      { id: "7-2", title: "Contact available CNAs", completed: true },
      { id: "7-3", title: "Confirm replacements", completed: true },
      { id: "7-4", title: "Update schedule in system", completed: false },
    ],
    comments: [
      { id: "c7-1", author: "Shift", text: "Found 2 available CNAs. Both confirmed for Saturday and Sunday.", created_at: hoursAgo(6) },
      { id: "c7-2", author: "Terra", text: "Good work. Update the schedule and I will sign off.", created_at: hoursAgo(4) },
    ],
  },
  {
    id: "8",
    title: "Collect family testimonial - Johnson family",
    description: "The Johnson family expressed deep gratitude. Reach out to collect a written or video testimonial for our website.",
    status: "todo",
    priority: "normal",
    assigned_agent_id: "memory",
    department_id: "customer-experience",
    deadline: daysFromNow(14),
    created_at: daysAgo(3),
    last_viewed_by: null,
    last_viewed_at: null,
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["testimonial", "family", "content"],
    subtasks: [
      { id: "8-1", title: "Send initial outreach email", completed: false },
      { id: "8-2", title: "Follow up with phone call", completed: false },
      { id: "8-3", title: "Schedule recording or collect written", completed: false },
    ],
    comments: [],
  },
  {
    id: "9",
    title: "Submit monthly financial package",
    description: "Compile and submit the March 2026 financial reporting package. P&L, balance sheet, cash flow, AR aging.",
    status: "blocked",
    priority: "critical",
    assigned_agent_id: "steward",
    department_id: "accounting-finance",
    deadline: daysAgo(2),
    created_at: daysAgo(8),
    last_viewed_by: "Lamin",
    last_viewed_at: hoursAgo(3),
    sign_off_required: true,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["financial", "monthly", "reporting", "blocked"],
    subtasks: [
      { id: "9-1", title: "Close March books", completed: true },
      { id: "9-2", title: "Generate P&L statement", completed: true },
      { id: "9-3", title: "Generate balance sheet", completed: true },
      { id: "9-4", title: "AR aging report", completed: false },
      { id: "9-5", title: "Cash flow statement", completed: false },
      { id: "9-6", title: "Package and submit", completed: false },
    ],
    comments: [
      { id: "c9-1", author: "Steward", text: "Blocked — waiting on Harvest to reconcile 3 Medicare payments from Q1 audit.", created_at: daysAgo(1) },
      { id: "c9-2", author: "Harvest", text: "Working on it. Should have reconciliation by tomorrow.", created_at: hoursAgo(8) },
    ],
  },
  {
    id: "10",
    title: "Plan community grief workshop",
    description: "Organize a free community grief support workshop. Partner with local churches and community centers.",
    status: "backlog",
    priority: "low",
    assigned_agent_id: "gather",
    department_id: "marketing",
    deadline: daysFromNow(45),
    created_at: daysAgo(6),
    last_viewed_by: null,
    last_viewed_at: null,
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["community", "grief", "workshop", "event"],
    subtasks: [
      { id: "10-1", title: "Research venue options", completed: false },
      { id: "10-2", title: "Draft workshop agenda", completed: false },
      { id: "10-3", title: "Identify speaker/facilitator", completed: false },
    ],
    comments: [],
  },
  {
    id: "11",
    title: "Run SEO analysis on competitor sites",
    description: "Completed analysis of top 5 competitor hospice websites in Bucks County. Report delivered to Camila.",
    status: "done",
    priority: "normal",
    assigned_agent_id: "roots",
    department_id: "marketing",
    deadline: daysAgo(3),
    created_at: daysAgo(12),
    last_viewed_by: "Camila",
    last_viewed_at: daysAgo(3),
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["seo", "competitor", "analysis"],
    subtasks: [
      { id: "11-1", title: "Identify top 5 competitors", completed: true },
      { id: "11-2", title: "Run SEMrush analysis", completed: true },
      { id: "11-3", title: "Compile report with recommendations", completed: true },
    ],
    comments: [
      { id: "c11-1", author: "Roots", text: "Report complete. Key finding: we rank #4 for 'hospice Bucks County'. Recommendations included.", created_at: daysAgo(3) },
      { id: "c11-2", author: "Camila", text: "Excellent work. Will incorporate into Q2 content strategy.", created_at: daysAgo(3) },
    ],
  },
  {
    id: "12",
    title: "Verify insurance for new admission",
    description: "Verify insurance coverage and benefits for pending admission — patient transferring from Doylestown Hospital.",
    status: "in_progress",
    priority: "high",
    assigned_agent_id: "verify",
    department_id: "admissions-intake",
    deadline: daysFromNow(1),
    created_at: daysAgo(2),
    last_viewed_by: "River",
    last_viewed_at: hoursAgo(5),
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["insurance", "admission", "verification"],
    subtasks: [
      { id: "12-1", title: "Contact insurance provider", completed: true },
      { id: "12-2", title: "Verify hospice benefit", completed: false },
      { id: "12-3", title: "Document authorization", completed: false },
    ],
    comments: [
      { id: "c12-1", author: "Verify", text: "Called Aetna. On hold for eligibility team. Will update once confirmed.", created_at: hoursAgo(2) },
    ],
  },
  {
    id: "13",
    title: "Review bereavement program month 6 contacts",
    description: "Check in on families at the 6-month mark in our 13-month bereavement program. Send personalized letters and schedule calls.",
    status: "todo",
    priority: "normal",
    assigned_agent_id: "bereavement",
    department_id: "clinical-operations",
    deadline: daysFromNow(7),
    created_at: daysAgo(2),
    last_viewed_by: null,
    last_viewed_at: null,
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["bereavement", "family", "follow-up"],
    subtasks: [
      { id: "13-1", title: "Pull list of month-6 families", completed: false },
      { id: "13-2", title: "Personalize letters", completed: false },
      { id: "13-3", title: "Schedule follow-up calls", completed: false },
    ],
    comments: [],
  },
  {
    id: "14",
    title: "Prepare mock survey checklist",
    description: "Create comprehensive mock survey checklist based on latest CMS Conditions of Participation. Use for internal readiness drill.",
    status: "backlog",
    priority: "high",
    assigned_agent_id: "guardian",
    department_id: "compliance-quality",
    deadline: daysFromNow(14),
    created_at: daysAgo(4),
    last_viewed_by: "Justice",
    last_viewed_at: daysAgo(2),
    sign_off_required: true,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["survey", "compliance", "cms", "checklist"],
    subtasks: [
      { id: "14-1", title: "Review latest CoP requirements", completed: false },
      { id: "14-2", title: "Draft checklist sections", completed: false },
      { id: "14-3", title: "Review with Justice", completed: false },
      { id: "14-4", title: "Schedule mock drill", completed: false },
    ],
    comments: [
      { id: "c14-1", author: "Justice", text: "Prioritize patient rights and infection control sections. Those are top survey focus areas.", created_at: daysAgo(2) },
    ],
  },
  {
    id: "15",
    title: "Post 3 new CNA positions on Indeed",
    description: "Posted 3 CNA positions on Indeed, ZipRecruiter, and LinkedIn. Applications are flowing in.",
    status: "done",
    priority: "normal",
    assigned_agent_id: "recruit",
    department_id: "caregiver-staffing",
    deadline: daysAgo(5),
    created_at: daysAgo(10),
    last_viewed_by: "Terra",
    last_viewed_at: daysAgo(4),
    sign_off_required: false,
    signed_off_by: null,
    signed_off_at: null,
    tags: ["recruiting", "cna", "job-posting"],
    subtasks: [
      { id: "15-1", title: "Write job descriptions", completed: true },
      { id: "15-2", title: "Post on Indeed", completed: true },
      { id: "15-3", title: "Post on ZipRecruiter", completed: true },
      { id: "15-4", title: "Post on LinkedIn", completed: true },
    ],
    comments: [
      { id: "c15-1", author: "Recruit", text: "All 3 positions live. Already received 12 applications in first 48 hours.", created_at: daysAgo(5) },
      { id: "c15-2", author: "Terra", text: "Great response rate. Start screening top candidates.", created_at: daysAgo(4) },
    ],
  },
];
